/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import contract.CinemaRMI;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import contract.dto.FilmeDTO;

/**
 *
 * @author wende
 */
public class Main extends javax.swing.JFrame {
    
    private CinemaRMI cinemaService;

    public Main(CinemaRMI cinemaService) {
        initComponents();
        this.cinemaService = cinemaService; // Você já tem isso, está perfeito!

        // Configurações da tabela que você já tem
        jTableFilmesCartaz.setRowSelectionAllowed(true);
        jTableFilmesCartaz.setColumnSelectionAllowed(false);
        jTableFilmesCartaz.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // CHAME O NOVO MÉTODO AQUI
        carregarFilmes(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilmes = new javax.swing.JPanel();
        jLTituloPageMain = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilmesCartaz = new javax.swing.JTable();
        jBtnVerSecoes = new javax.swing.JButton();

        jPanelFilmes.setBackground(new java.awt.Color(33, 33, 33));

        jLTituloPageMain.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLTituloPageMain.setForeground(new java.awt.Color(224, 224, 224));
        jLTituloPageMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloPageMain.setText("Filmes em Cartaz");

        jTableFilmesCartaz.setBackground(new java.awt.Color(33, 33, 33));
        jTableFilmesCartaz.setForeground(new java.awt.Color(224, 224, 224));
        jTableFilmesCartaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Filme 1", "teste", "16"},
                { new Integer(2), "Filme 2", "teste", "16"},
                { new Integer(3), "Filme 3", "teste", "16"},
                { new Integer(4), "Filme 4", "teste", "16"},
                { new Integer(5), "Filme 5", "teste", "16"}
            },
            new String [] {
                "ID", "Titulo do Filme", "Genero", "Classificação Indicativa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableFilmesCartaz.setColumnSelectionAllowed(true);
        jTableFilmesCartaz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableFilmesCartaz.setGridColor(new java.awt.Color(66, 66, 66));
        jTableFilmesCartaz.setMaximumSize(new java.awt.Dimension(2147483647, 260));
        jTableFilmesCartaz.setMinimumSize(new java.awt.Dimension(100, 260));
        jTableFilmesCartaz.setNextFocusableComponent(jBtnVerSecoes);
        jTableFilmesCartaz.setPreferredSize(new java.awt.Dimension(225, 260));
        jTableFilmesCartaz.setRowHeight(30);
        jTableFilmesCartaz.setSelectionBackground(new java.awt.Color(229, 9, 20));
        jTableFilmesCartaz.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableFilmesCartaz.setShowGrid(true);
        jTableFilmesCartaz.setShowHorizontalLines(true);
        jTableFilmesCartaz.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableFilmesCartaz);
        jTableFilmesCartaz.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableFilmesCartaz.getColumnModel().getColumnCount() > 0) {
            jTableFilmesCartaz.getColumnModel().getColumn(3).setMinWidth(70);
        }

        jBtnVerSecoes.setBackground(new java.awt.Color(229, 9, 20));
        jBtnVerSecoes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVerSecoes.setText("VER SEÇÕES");
        jBtnVerSecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVerSecoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilmesLayout = new javax.swing.GroupLayout(jPanelFilmes);
        jPanelFilmes.setLayout(jPanelFilmesLayout);
        jPanelFilmesLayout.setHorizontalGroup(
            jPanelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFilmesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLTituloPageMain, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(jPanelFilmesLayout.createSequentialGroup()
                .addGroup(jPanelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilmesLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFilmesLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jBtnVerSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        jPanelFilmesLayout.setVerticalGroup(
            jPanelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilmesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTituloPageMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnVerSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVerSecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVerSecoesActionPerformed
        int linhaSelecionada = jTableFilmesCartaz.getSelectedRow();

        // (getSelectedRow() retorna -1 )
        if (linhaSelecionada != -1) {

            Object idObjeto = jTableFilmesCartaz.getValueAt(linhaSelecionada, 0);
            Object NomeObject = jTableFilmesCartaz.getValueAt(linhaSelecionada, 1);

            int idDoFilme = Integer.parseInt(idObjeto.toString());
            String nomeFilme = NomeObject.toString();

            System.out.println("ID do filme selecionado: " + idDoFilme);

            Sessoes telaSessoes = new Sessoes(idDoFilme, nomeFilme, cinemaService);
            telaSessoes.setVisible(true);
            this.dispose();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um filme na lista.");
        }   
    }//GEN-LAST:event_jBtnVerSecoesActionPerformed
    
    private void carregarFilmes(){
        final DefaultTableModel model = (DefaultTableModel) jTableFilmesCartaz.getModel();
        
        model.setRowCount(0);
        
        jLTituloPageMain.setText("Carregando filmes...");
        
        SwingWorker<java.util.List<contract.dto.FilmeDTO>, Void> worker = new SwingWorker<java.util.List<contract.dto.FilmeDTO>, Void>() {
            @Override
            protected List<FilmeDTO> doInBackground() throws Exception {
                // 1. ESTA É A CHAMADA RMI! Executa em uma thread separada.
                return cinemaService.listarFilmes();
            }

            @Override
            protected void done() {
                try {
                    // 2. Pega o resultado da chamada RMI quando ela terminar
                    List<FilmeDTO> filmes = get();

                    // 3. Preenche a tabela com os filmes recebidos do servidor
                    for (FilmeDTO filme : filmes) {
                        model.addRow(new Object[]{
                            filme.getId(),
                            filme.getTitulo(),
                            filme.getGenero(),
                            filme.getClassificacaoIndicativa()
                        });
                    }

                    jLTituloPageMain.setText("Filmes em Cartaz"); // Restaura o título

                } catch (Exception e) {
                    // 4. Se a conexão falhar, mostra uma mensagem de erro
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(
                        Main.this, // "this" se refere à instância de Main
                        "Erro ao carregar filmes do servidor.",
                        "Erro de Conexão",
                        JOptionPane.ERROR_MESSAGE
                    );
                    jLTituloPageMain.setText("Falha ao carregar");
                }
            }
        };
        
        worker.execute();
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVerSecoes;
    private javax.swing.JLabel jLTituloPageMain;
    private javax.swing.JPanel jPanelFilmes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilmesCartaz;
    // End of variables declaration//GEN-END:variables
}
