/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.security.Principal;
import javax.swing.SwingUtilities;

/**
 *
 * @author wende
 */
public class Poltronas extends javax.swing.JInternalFrame {

    private javax.swing.JButton poltronaSelecionada = null;

    // Adicione estas constantes de cor para facilitar a manutenção.
    private final java.awt.Color COR_DISPONIVEL = java.awt.Color.decode("#424242");
    private final java.awt.Color COR_OCUPADA = java.awt.Color.decode("#999999");
    private final java.awt.Color COR_SELECIONADA = java.awt.Color.decode("#007BFF");
    
    public Poltronas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLTituloSecoes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNomeCliente = new javax.swing.JTextField();
        jBPolB1 = new javax.swing.JButton();
        jBPolC1 = new javax.swing.JButton();
        jBPolA1 = new javax.swing.JButton();
        jBPolF1 = new javax.swing.JButton();
        jBPolG1 = new javax.swing.JButton();
        jBPolD1 = new javax.swing.JButton();
        jBPolE1 = new javax.swing.JButton();
        jBPolF2 = new javax.swing.JButton();
        jBPolG2 = new javax.swing.JButton();
        jBPolD2 = new javax.swing.JButton();
        jBPolE2 = new javax.swing.JButton();
        jBPolB2 = new javax.swing.JButton();
        jBPolC2 = new javax.swing.JButton();
        jBPolA2 = new javax.swing.JButton();
        jBPolF3 = new javax.swing.JButton();
        jBPolG3 = new javax.swing.JButton();
        jBPolD3 = new javax.swing.JButton();
        jBPolE3 = new javax.swing.JButton();
        jBPolB3 = new javax.swing.JButton();
        jBPolC3 = new javax.swing.JButton();
        jBPolA3 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        jButton1.setBackground(new java.awt.Color(76, 175, 80));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("COMPRAR INGRESSO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLTituloSecoes.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLTituloSecoes.setForeground(new java.awt.Color(224, 224, 224));
        jLTituloSecoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloSecoes.setText("Escolha sua poltrona - Sala");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite seu Nome:");

        jTFNomeCliente.setBackground(new java.awt.Color(66, 66, 66));
        jTFNomeCliente.setForeground(new java.awt.Color(224, 224, 224));

        jBPolB1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolB1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolB1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolB1.setText("B1");
        jBPolB1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolB1ActionPerformed(evt);
            }
        });

        jBPolC1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolC1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolC1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolC1.setText("C1");
        jBPolC1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolC1ActionPerformed(evt);
            }
        });

        jBPolA1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolA1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolA1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolA1.setText("A1");
        jBPolA1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolA1ActionPerformed(evt);
            }
        });

        jBPolF1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolF1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolF1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolF1.setText("F1");
        jBPolF1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolF1ActionPerformed(evt);
            }
        });

        jBPolG1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolG1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolG1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolG1.setText("G1");
        jBPolG1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolG1ActionPerformed(evt);
            }
        });

        jBPolD1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolD1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolD1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolD1.setText("D1");
        jBPolD1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolD1ActionPerformed(evt);
            }
        });

        jBPolE1.setBackground(new java.awt.Color(66, 66, 66));
        jBPolE1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolE1.setForeground(new java.awt.Color(224, 224, 224));
        jBPolE1.setText("E1");
        jBPolE1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolE1ActionPerformed(evt);
            }
        });

        jBPolF2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolF2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolF2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolF2.setText("F2");
        jBPolF2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolF2ActionPerformed(evt);
            }
        });

        jBPolG2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolG2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolG2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolG2.setText("G2");

        jBPolG2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolG2ActionPerformed(evt);
            }
        });

        jBPolD2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolD2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolD2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolD2.setText("D2");
        jBPolD2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolD2ActionPerformed(evt);
            }
        });

        jBPolE2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolE2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolE2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolE2.setText("E2");
        jBPolE2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolE2ActionPerformed(evt);
            }
        });

        jBPolB2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolB2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolB2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolB2.setText("B2");
        jBPolB2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolB2ActionPerformed(evt);
            }
        });

        jBPolC2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolC2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolC2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolC2.setText("C2");
        jBPolC2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolC2ActionPerformed(evt);
            }
        });

        jBPolA2.setBackground(new java.awt.Color(66, 66, 66));
        jBPolA2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolA2.setForeground(new java.awt.Color(224, 224, 224));
        jBPolA2.setText("A2");
        jBPolA2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolA2ActionPerformed(evt);
            }
        });

        jBPolF3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolF3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolF3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolF3.setText("F3");
        jBPolF3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolF3ActionPerformed(evt);
            }
        });

        jBPolG3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolG3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolG3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolG3.setText("G3");
        jBPolG3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolG3ActionPerformed(evt);
            }
        });

        jBPolD3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolD3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolD3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolD3.setText("D3");
        jBPolD3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolD3ActionPerformed(evt);
            }
        });

        jBPolE3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolE3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolE3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolE3.setText("E3");
        jBPolE3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolE3ActionPerformed(evt);
            }
        });

        jBPolB3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolB3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolB3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolB3.setText("B3");
        jBPolB3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolB3ActionPerformed(evt);
            }
        });

        jBPolC3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolC3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolC3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolC3.setText("C3");
        jBPolC3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolC3ActionPerformed(evt);
            }
        });

        jBPolA3.setBackground(new java.awt.Color(66, 66, 66));
        jBPolA3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jBPolA3.setForeground(new java.awt.Color(224, 224, 224));
        jBPolA3.setText("A3");
        jBPolA3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jBPolA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPolA3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLTituloSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jBPolA1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBPolB1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jBPolC1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBPolD1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBPolE1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBPolF1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBPolG1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBPolA3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolB3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolC3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolD3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolE3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolF3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolG3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBPolA2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolB2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolC2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolD2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolE2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolF2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBPolG2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLTituloSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPolB1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolC1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolF1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolG1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolA1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolD1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolE1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPolB2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolC2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolF2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolG2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolA2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolD2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolE2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPolB3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolC3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolF3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolG3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolA3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolD3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPolE3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBPolA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolA1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolA1ActionPerformed

    private void jBPolB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolB1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolB1ActionPerformed

    private void jBPolC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolC1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolC1ActionPerformed

    private void jBPolD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolD1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolD1ActionPerformed

    private void jBPolE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolE1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolE1ActionPerformed

    private void jBPolF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolF1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolF1ActionPerformed

    private void jBPolG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolG1ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolG1ActionPerformed

    private void jBPolA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolA2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolA2ActionPerformed

    private void jBPolB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolB2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolB2ActionPerformed

    private void jBPolC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolC2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolC2ActionPerformed

    private void jBPolD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolD2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolD2ActionPerformed

    private void jBPolE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolE2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolE2ActionPerformed

    private void jBPolF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolF2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolF2ActionPerformed

    private void jBPolG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolG2ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolG2ActionPerformed

    private void jBPolA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolA3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolA3ActionPerformed

    private void jBPolB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolB3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolB3ActionPerformed

    private void jBPolC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolC3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolC3ActionPerformed

    private void jBPolD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolD3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolD3ActionPerformed

    private void jBPolE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolE3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolE3ActionPerformed

    private void jBPolF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolF3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolF3ActionPerformed

    private void jBPolG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPolG3ActionPerformed
        PoltronasPerformadSelection(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBPolG3ActionPerformed
    
    private void PoltronasPerformadSelection(java.awt.event.ActionEvent evt){
        javax.swing.JButton botaoClicado = (javax.swing.JButton) evt.getSource();

        // Se o botão clicado já estiver ocupado, não faz nada.
        if (botaoClicado.getBackground().equals(COR_OCUPADA)) {
            return;
        }

        // Se já existia uma poltrona selecionada anteriormente...
        if (poltronaSelecionada != null) {
            // ...pinta ela de volta com a cor de "disponível".
            poltronaSelecionada.setBackground(COR_DISPONIVEL);
        }

        // Pinta o novo botão clicado com a cor de "selecionado".
        botaoClicado.setBackground(COR_SELECIONADA);

        // Agora, atualiza a variável para guardar este novo botão como o selecionado.
        poltronaSelecionada = botaoClicado;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPolA1;
    private javax.swing.JButton jBPolA2;
    private javax.swing.JButton jBPolA3;
    private javax.swing.JButton jBPolB1;
    private javax.swing.JButton jBPolB2;
    private javax.swing.JButton jBPolB3;
    private javax.swing.JButton jBPolC1;
    private javax.swing.JButton jBPolC2;
    private javax.swing.JButton jBPolC3;
    private javax.swing.JButton jBPolD1;
    private javax.swing.JButton jBPolD2;
    private javax.swing.JButton jBPolD3;
    private javax.swing.JButton jBPolE1;
    private javax.swing.JButton jBPolE2;
    private javax.swing.JButton jBPolE3;
    private javax.swing.JButton jBPolF1;
    private javax.swing.JButton jBPolF2;
    private javax.swing.JButton jBPolF3;
    private javax.swing.JButton jBPolG1;
    private javax.swing.JButton jBPolG2;
    private javax.swing.JButton jBPolG3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLTituloSecoes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFNomeCliente;
    // End of variables declaration//GEN-END:variables
}
