/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import contract.CinemaRMI;
import contract.model.SessaoModel;

/**
 *
 * @author wende
 */
public class Sessoes extends javax.swing.JFrame {

    /**
     * Creates new form Secoes
     * @param id
     */
    
    private CinemaRMI cinemaService;
    int filmeId = 0;
    
    public Sessoes(int idDoFilme, String NomeFilme, CinemaRMI service) {
        
        this.filmeId = idDoFilme;
        this.cinemaService = service;
        
        initComponents();
        
        String textoAtual = jLTituloSecoes.getText();
        jLTituloSecoes.setText(textoAtual + " " + NomeFilme);
        
        carregarSessoes();
    }
    
    private void carregarSessoes(){
        final javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableSessoes.getModel();
    
        model.setRowCount(0);
        
        jLabelStatus.setText("Carregando sessões...");
        
        SwingWorker<List<SessaoModel>, Void> worker = new SwingWorker<List<SessaoModel>, Void>() {
            @Override
            protected List<SessaoModel> doInBackground() throws Exception{
                return cinemaService.listarSessoesPorFilme(filmeId);
            }
                
            @Override
            protected void done(){
                try{
                    List<SessaoModel> sessoes = get();

                    for (SessaoModel sessao : sessoes){
                        model.addRow(new  Object[]{
                            sessao.getId(),
                            sessao.getDataHora(),
                            sessao.getSalaId(),
                            sessao.getPrecoIngresso()
                        });
                    }

                    jLabelStatus.setText("Sessoes carregadas.");
                }catch (Exception e){
                    e.printStackTrace();
                    jLabelStatus.setText("Erro ao carregar sessões");
                    JOptionPane.showMessageDialog(
                        Sessoes.this,
                        "Não foi possível conectar ao servidor para buscar as sessões.",
                        "Erro de Conexão",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        };

        worker.execute();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLTituloSecoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSessoes = new javax.swing.JTable();
        jBtnSecoes = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 224, 224));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filmes em Cartaz");

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        jLTituloSecoes.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLTituloSecoes.setForeground(new java.awt.Color(224, 224, 224));
        jLTituloSecoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloSecoes.setText("Sessões para");

        jTableSessoes.setBackground(new java.awt.Color(33, 33, 33));
        jTableSessoes.setForeground(new java.awt.Color(255, 255, 255));
        jTableSessoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "25/10/2025", "13:15",  new Integer(130),  new Double(12.4)},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Hora", "Sala", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableSessoes.setToolTipText("");
        jTableSessoes.setColumnSelectionAllowed(true);
        jTableSessoes.setGridColor(new java.awt.Color(102, 102, 102));
        jTableSessoes.setShowGrid(false);
        jTableSessoes.setShowHorizontalLines(true);
        jTableSessoes.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTableSessoes);
        jTableSessoes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableSessoes.getColumnModel().getColumnCount() > 0) {
            jTableSessoes.getColumnModel().getColumn(1).setResizable(false);
            jTableSessoes.getColumnModel().getColumn(2).setResizable(false);
            jTableSessoes.getColumnModel().getColumn(3).setResizable(false);
            jTableSessoes.getColumnModel().getColumn(4).setResizable(false);
        }

        jBtnSecoes.setBackground(new java.awt.Color(229, 9, 20));
        jBtnSecoes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSecoes.setText("ESCOLHER POLTRONAS");
        jBtnSecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSecoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLTituloSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBtnSecoes)
                        .addGap(108, 108, 108)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTituloSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSecoesActionPerformed
        int linhaSelecionada = jTableSessoes.getSelectedRow();

        // (getSelectedRow() retorna -1 )
        if (linhaSelecionada != -1) {

            Object idObjeto = jTableSessoes.getValueAt(linhaSelecionada, 0);
            Object SalaObject = jTableSessoes.getValueAt(linhaSelecionada, 2);

            int idDaSala = Integer.parseInt(idObjeto.toString());
            int numeroSala = Integer.parseInt(SalaObject.toString());

            System.out.println("ID do filme selecionado: " + idDaSala);

            Poltronas telaPoltronas = new Poltronas(idDaSala, numeroSala, cinemaService);
            // Poltronas was implemented as a JInternalFrame. To show it from this JFrame
            // we wrap its content into a temporary JFrame so it appears as a standalone window.
            javax.swing.JFrame wrapper = new javax.swing.JFrame("Poltronas - Sala " + numeroSala);
            wrapper.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            wrapper.setContentPane(telaPoltronas.getContentPane());
            wrapper.pack();
            wrapper.setLocationRelativeTo(this);
            wrapper.setVisible(true);
            this.dispose();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um filme na lista.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSecoesActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSecoes;
    private javax.swing.JLabel jLTituloSecoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSessoes;
    // End of variables declaration//GEN-END:variables
}
